# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apme.v1 import cache_pb2 as apme_dot_v1_dot_cache__pb2
from apme.v1 import common_pb2 as apme_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apme/v1/cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CacheMaintainerStub(object):
    """CacheMaintainer populates the collection cache (Galaxy + GitHub); scales independently.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullGalaxy = channel.unary_unary(
                '/apme.v1.CacheMaintainer/PullGalaxy',
                request_serializer=apme_dot_v1_dot_cache__pb2.PullGalaxyRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_cache__pb2.PullGalaxyResponse.FromString,
                _registered_method=True)
        self.PullRequirements = channel.unary_unary(
                '/apme.v1.CacheMaintainer/PullRequirements',
                request_serializer=apme_dot_v1_dot_cache__pb2.PullRequirementsRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_cache__pb2.PullRequirementsResponse.FromString,
                _registered_method=True)
        self.CloneOrg = channel.unary_unary(
                '/apme.v1.CacheMaintainer/CloneOrg',
                request_serializer=apme_dot_v1_dot_cache__pb2.CloneOrgRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_cache__pb2.CloneOrgResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/apme.v1.CacheMaintainer/Health',
                request_serializer=apme_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class CacheMaintainerServicer(object):
    """CacheMaintainer populates the collection cache (Galaxy + GitHub); scales independently.
    """

    def PullGalaxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullRequirements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloneOrg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheMaintainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullGalaxy': grpc.unary_unary_rpc_method_handler(
                    servicer.PullGalaxy,
                    request_deserializer=apme_dot_v1_dot_cache__pb2.PullGalaxyRequest.FromString,
                    response_serializer=apme_dot_v1_dot_cache__pb2.PullGalaxyResponse.SerializeToString,
            ),
            'PullRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.PullRequirements,
                    request_deserializer=apme_dot_v1_dot_cache__pb2.PullRequirementsRequest.FromString,
                    response_serializer=apme_dot_v1_dot_cache__pb2.PullRequirementsResponse.SerializeToString,
            ),
            'CloneOrg': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneOrg,
                    request_deserializer=apme_dot_v1_dot_cache__pb2.CloneOrgRequest.FromString,
                    response_serializer=apme_dot_v1_dot_cache__pb2.CloneOrgResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=apme_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=apme_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apme.v1.CacheMaintainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apme.v1.CacheMaintainer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CacheMaintainer(object):
    """CacheMaintainer populates the collection cache (Galaxy + GitHub); scales independently.
    """

    @staticmethod
    def PullGalaxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.CacheMaintainer/PullGalaxy',
            apme_dot_v1_dot_cache__pb2.PullGalaxyRequest.SerializeToString,
            apme_dot_v1_dot_cache__pb2.PullGalaxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.CacheMaintainer/PullRequirements',
            apme_dot_v1_dot_cache__pb2.PullRequirementsRequest.SerializeToString,
            apme_dot_v1_dot_cache__pb2.PullRequirementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloneOrg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.CacheMaintainer/CloneOrg',
            apme_dot_v1_dot_cache__pb2.CloneOrgRequest.SerializeToString,
            apme_dot_v1_dot_cache__pb2.CloneOrgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.CacheMaintainer/Health',
            apme_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            apme_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
