# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apme/v1/cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apme/v1/cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apme.v1 import common_pb2 as apme_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pme/v1/cache.proto\x12\x07\x61pme.v1\x1a\x14\x61pme/v1/common.proto\"8\n\x11PullGalaxyRequest\x12\x0c\n\x04spec\x18\x01 \x01(\t\x12\x15\n\rgalaxy_server\x18\x02 \x01(\t\"J\n\x12PullGalaxyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"K\n\x17PullRequirementsRequest\x12\x19\n\x11requirements_path\x18\x01 \x01(\t\x12\x15\n\rgalaxy_server\x18\x02 \x01(\t\"Q\n\x18PullRequirementsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05paths\x18\x02 \x03(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"K\n\x0f\x43loneOrgRequest\x12\x0b\n\x03org\x18\x01 \x01(\t\x12\r\n\x05repos\x18\x02 \x03(\t\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\x12\r\n\x05token\x18\x04 \x01(\t\"I\n\x10\x43loneOrgResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05paths\x18\x02 \x03(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xad\x02\n\x0f\x43\x61\x63heMaintainer\x12\x45\n\nPullGalaxy\x12\x1a.apme.v1.PullGalaxyRequest\x1a\x1b.apme.v1.PullGalaxyResponse\x12W\n\x10PullRequirements\x12 .apme.v1.PullRequirementsRequest\x1a!.apme.v1.PullRequirementsResponse\x12?\n\x08\x43loneOrg\x12\x18.apme.v1.CloneOrgRequest\x1a\x19.apme.v1.CloneOrgResponse\x12\x39\n\x06Health\x12\x16.apme.v1.HealthRequest\x1a\x17.apme.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apme.v1.cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PULLGALAXYREQUEST']._serialized_start=54
  _globals['_PULLGALAXYREQUEST']._serialized_end=110
  _globals['_PULLGALAXYRESPONSE']._serialized_start=112
  _globals['_PULLGALAXYRESPONSE']._serialized_end=186
  _globals['_PULLREQUIREMENTSREQUEST']._serialized_start=188
  _globals['_PULLREQUIREMENTSREQUEST']._serialized_end=263
  _globals['_PULLREQUIREMENTSRESPONSE']._serialized_start=265
  _globals['_PULLREQUIREMENTSRESPONSE']._serialized_end=346
  _globals['_CLONEORGREQUEST']._serialized_start=348
  _globals['_CLONEORGREQUEST']._serialized_end=423
  _globals['_CLONEORGRESPONSE']._serialized_start=425
  _globals['_CLONEORGRESPONSE']._serialized_end=498
  _globals['_CACHEMAINTAINER']._serialized_start=501
  _globals['_CACHEMAINTAINER']._serialized_end=802
# @@protoc_insertion_point(module_scope)
