# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apme/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apme/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pme/v1/common.proto\x12\x07\x61pme.v1\"\xa0\x01\n\tViolation\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\t\x12\x0e\n\x04line\x18\x05 \x01(\x05H\x00\x12(\n\nline_range\x18\x06 \x01(\x0b\x32\x12.apme.v1.LineRangeH\x00\x12\x0c\n\x04path\x18\x07 \x01(\tB\x0c\n\nline_oneof\"\'\n\tLineRange\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"%\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"E\n\nRuleTiming\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x12\n\nelapsed_ms\x18\x02 \x01(\x01\x12\x12\n\nviolations\x18\x03 \x01(\x05\"\xa1\x02\n\x14ValidatorDiagnostics\x12\x16\n\x0evalidator_name\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x10\n\x08total_ms\x18\x03 \x01(\x01\x12\x16\n\x0e\x66iles_received\x18\x04 \x01(\x05\x12\x18\n\x10violations_found\x18\x05 \x01(\x05\x12)\n\x0crule_timings\x18\x06 \x03(\x0b\x32\x13.apme.v1.RuleTiming\x12=\n\x08metadata\x18\x07 \x03(\x0b\x32+.apme.v1.ValidatorDiagnostics.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apme.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATORDIAGNOSTICS_METADATAENTRY']._loaded_options = None
  _globals['_VALIDATORDIAGNOSTICS_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VIOLATION']._serialized_start=34
  _globals['_VIOLATION']._serialized_end=194
  _globals['_LINERANGE']._serialized_start=196
  _globals['_LINERANGE']._serialized_end=235
  _globals['_FILE']._serialized_start=237
  _globals['_FILE']._serialized_end=274
  _globals['_HEALTHREQUEST']._serialized_start=276
  _globals['_HEALTHREQUEST']._serialized_end=291
  _globals['_HEALTHRESPONSE']._serialized_start=293
  _globals['_HEALTHRESPONSE']._serialized_end=325
  _globals['_RULETIMING']._serialized_start=327
  _globals['_RULETIMING']._serialized_end=396
  _globals['_VALIDATORDIAGNOSTICS']._serialized_start=399
  _globals['_VALIDATORDIAGNOSTICS']._serialized_end=688
  _globals['_VALIDATORDIAGNOSTICS_METADATAENTRY']._serialized_start=641
  _globals['_VALIDATORDIAGNOSTICS_METADATAENTRY']._serialized_end=688
# @@protoc_insertion_point(module_scope)
